Move common functionality from `markprompt` to `@markprompt/core`
motifland/markprompt pull request #33
Opened 2023-04-09 12:37 UTC by nickrttn

- Move markprompt to a namespaced package @markprompt/react
- Move common functionality to `@markprompt/core`
- Consume `@markprompt/core` in `@markprompt/react`

2023-04-10 15:28 UTC, michaelfester approved these changes
Looks great! 👍

2023-04-14 11:50 UTC, remcohaszing requested changes

2023-04-14 11:50 UTC, remcohaszing commented on .gitignore
> +.env
Could you rebase? I added this in the main branch.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/.gitignore
Can you remove this file? `*.tsbuildinfo` is already gitiginored in `/.gitignore`.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/README.md
> +Currently,
I think you were typing something here. Let’s finish that sentence or remove it.

```suggestion

Currently,
```

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.d.ts
This file is generated. Let’s not commit it.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.d.ts.map
This file is generated. Let’s not commit it.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.js
We could use TypeScript or types in jsdoc, but IMO it’s best to keep it consistent.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.js
> +export const submitPrompt = async function (
```suggestion
export async function submitPrompt (
```

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.js
> +  );
I think a simple spread would work here as well.

```suggestion
  options = {
    ...defaultOptions,
    ...options
  };
```

It may also be better to not reassign to function parameters.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.js
> +};
Just an idea:

We could use an iterator instead of a callback.

```ts
let answer = ''

for (await const chunk of submitPrompt(/* … */)) {
  answer += chunk
}
```

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.js
> +    onAnswerChunk(options.iDontKnowMessage);
I think logging errors is ok for application code, but not for library code. The consumer of this package needs to be able to handle the error. We could add it as the second argument of the `onAnswerChunk` message for example, or not handle it at all.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/index.js
> +    const res = await fetch(options.completionsUrl, {
Should we support `AbortController`?

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/yarn.lock
The main branch is now a yarn monorepo, so there’s no need to commit a lockfile per project anymore.

2023-04-14 11:50 UTC, remcohaszing commented on packages/core/package-lock.json
The main branch is now a yarn monorepo, so there’s no need to commit a lockfile per project anymore.

2023-04-14 12:07 UTC, nickrttn commented on packages/core/index.js
> +    const res = await fetch(options.completionsUrl, {
Yes, good idea :thumbsup:

2023-04-14 12:09 UTC, nickrttn commented on packages/core/index.js
> +};
Yes, I actually considered using an iterator (or generator) here. My main concern was that iterators or generators are not very common exports from library code and it might cause lots of issues being reported? On the other hand, we could document usage.

2023-04-14 12:13 UTC, nickrttn commented on packages/core/index.d.ts
In this case it seemed useful to commit it so we can completely skip building any build steps for this package on CI

2023-04-14 12:16 UTC, nickrttn commented on packages/core/index.js
I'm ok with either. Rationale here was to be able to skip build steps on CI, just run `tsc` locally after updates, commit and push.

2023-04-14 12:19 UTC, nickrttn commented on packages/core/index.js
> +  );
No, unfortunately won't work. When we consume this in `@markprompt/react` some values will be passed from optional props. That means that in the `options` object they can have `undefined` as a value. This makes sure that options that are defined but have `undefined` as a value will take the default value.

2023-04-14 12:20 UTC, remcohaszing commented on packages/core/index.js
> +};
I feel this sentiment too. Still, this seems like the perfect use case.

We could also export an additional function that just waits for the answer to be complete and return it as a single string. This is less powerful than streaming, but some users may want that.

Also think many users will use a framework integration (React). For them it doesn’t matter how this package works.

I feel like a generator makes sense here.

2023-04-14 12:29 UTC, nickrttn commented on packages/core/index.js
> +    onAnswerChunk(options.iDontKnowMessage);
I added a `onError` callback for now that is called with any errors.

2023-04-14 14:10 UTC, remcohaszing commented on packages/core/index.js
> +  );
Actually, it might may be even better to remove this statement, and below use:

```ts
JSON.stringify({
  prompt,
  model: options?.model ?? DEFAULT_MODEL,
  completionsUrl: options?.completionsUrl ?? MARKPROMPT_COMPLETIONS_URL,
  iDontKnowMessage: options?.iDontKnowMessage ?? I_DONT_KNOW_MESSAGE,
  promptTemplate: options?.promptTemplate,
  projectKey,
})
```

2023-04-14 14:24 UTC, nickrttn commented on packages/core/index.js
> +    const res = await fetch(options.completionsUrl, {
Added!

2023-04-14 16:07 UTC, michaelfester commented on packages/core/index.js
> +};
For a non-streaming API, this should be done at the OpenAI call level, which adds the `stream` flag.

2023-04-14 16:15 UTC, merged

2023-04-14 16:24 UTC, remcohaszing commented on packages/core/index.js
> +};
I don’t understand. This is about the function signature, not the API.